# Generated by Django 2.0.2 on 2018-11-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181104_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_pup',
            new_name='pup_date',
        ),
    ]
